name: Run count.py every minute

on:
  push:
    branches: [main] # change this to match your main branch name
  pull_request:
    branches: [main] # change this to match your main branch name
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run count.py
      run: |
        python count.py
